### ISSUE TITLE
All Forms displays wrong amounts

### ISSUE THREAD

**Issue by iMazed** [WordImpress/Give#2145] opened 2017-09-28 19:28 UTC
## Issue Overview

In the general **All Forms** page, the `Amount` column displays the donation amounts wrong. An extra two zeros are added to the minimum and maximum amount. 

I set up a form that takes donations from €5 up to €100. Here's how I set up the donation form: 

![2017-09-28 21_13_54-edit donation form donatewc wordpress](https://user-images.githubusercontent.com/3907432/30986141-c2d13908-a492-11e7-8f0c-9824f5fe38a4.jpg)

However, the **All Forms** overview looks like this:

![2017-09-28 21_13_10-donation forms donatewc wordpress](https://user-images.githubusercontent.com/3907432/30986204-ea5d121c-a492-11e7-8509-cd7310f7f6c6.jpg)

Also, the `Donations` and `Income` columns are set to zero, even though I have already received donations through this form. 

## Expected Behavior
 

I expect the **All Forms** overview to display the accurate numbers of the setup I've specified within the form. Also, an overview of what each form has 'collected' so far is helpful! 

## Current Behavior

Somewhere, two extra zeroes are added to the donation min-max numbers in the **All Forms** page, and the totals in the `Donations` and `Income` columns are faulty. The front end of the form works as expected though! 

## Possible Solution

No solution yet, but I've tried the following:
1. Changing the thousands and decimal separators. They're different from USD standards. This did not make a difference. 
2. I switched currency from EUR to USD. This did not make a difference.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment] 2017-09-28 19:55
Thanks @iMazed - we'll get this fixed in `1.8.15`

**Comment by ravinderk** [comment] 2017-09-29 10:03
@DevinWalker This issue already reported by @raftaar1191 here: https://github.com/WordImpress/Give/issues/1982#issuecomment-327935642
and working fine for me in `1.8.14`.

This was happing because `give_maybe_sanitize_amount` also sanitizing already sanitize number or decimal formatted number.

I will reopen this issue if somebody faces it again.

**Closed by ravinderk** 2017-09-29 10:03 UTC
Labels: bug, UI / UX

**Comment by DevinWalker** [comment] 2017-09-29 17:08
@ravinderk thanks for confirming - @iMazed we'll be releasing `1.8.14` soon. If you notice issues after updating please let me or @mathetos know. Thanks! Love what you're doing with the cause BTW.

**Comment by iMazed** [comment] 2017-10-02 10:53
Not sure if anyone has made any changes to the donatewc.org site/code that's running there, but the issue has now traveled from displaying wrong in the general overview to adding two zeroes to the form I'm trying to set up. 

![give](https://user-images.githubusercontent.com/3907432/31074374-9f8870a2-a770-11e7-8469-254fa07ef9ba.gif)

**Comment by ravinderk** [comment] 2017-10-02 11:54
@iMazed I was not able to reproduce this with `1.8.13`. We were facing an issue like this which we already fixed https://github.com/WordImpress/Give/issues/1982#issue-249739177 and it is working fine in `release/1.8.14`.

Sorry for your inconvenience.
