### ISSUE TITLE
Plugin Compatibility with SendGrid

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1054] opened 2016-09-23 23:26 UTC
## Issue Overview

Currently, if a user is using SendGrid and has "click and open tracking" enabled in the WordPress plugin settings, then it malforms our Donation Receipt email link. It swaps out the & for #038;  

Customer support ticket here:
https://secure.helpscout.net/conversation/250787186/3631/?folderId=672199
## Possible Solution

I don't think disabling "click and open tracking" is a good solution. But we have a "Plugin Compatibility" code for Mandrill that I'm hoping we can replicate for SendGrid
## Steps to Reproduce (for bugs)

I have a SendGrid account we can test with

**Comment by kevinwhoffman** [comment] 2017-02-01 06:52
I was able to confirm the issue exactly as the Help Scout ticket described.

When click and open tracking were enabled, I landed on the home page due to the encoded `&` as `#038;`. 

When I disable click and open tracking in SendGrid Settings > Tracking, then the link comes through untouched. Note: I had to disable _both_ click and open tracking in order for the link to come through clean. Otherwise SendGrid replaces the link with its own and redirects.

## Steps to Reproduce

1. Install Give 1.8.
2. Install [SendGrid plugin](https://wordpress.org/plugins/sendgrid-email-delivery-simplified/).
3. Enter SendGrid API key in plugin settings page.
4. Disable Give's test mode so the email receipt will send.
5. Make a donation.
6. Click receipt link in email and confirm you landed on home page rather than the intended receipt page. Look for `#038;` in the URL.

## Temporary Fix

1. Log in to SendGrid.
2. Go to Settings > Tracking.
3. Disable Click Tracking and Open Tracking.

**Comment by kevinwhoffman** [comment] 2017-02-01 07:04
Relevant support topics from the SendGrid plugin team:

- https://wordpress.org/support/topic/click-tracking-buddypress-ampersand/
- https://wordpress.org/support/topic/follow-up-password-reset-link-appears-to-be-invalid-unless-copied-and-pasted/

It seems they are aware of the issue but have not fixed it in at least 5 months since it was reported. We can't control how SendGrid formats a URL after a redirect so I'm not sure there's much else we can do other than recommend that Open/Click Tracking be disabled for the time being. This will allow the URLs to pass through cleanly without SendGrid redirecting them for tracking purposes.

**Comment by DevinWalker** [comment] 2017-02-01 18:04
Thanks for reviewing it.

**Closed by DevinWalker** 2017-02-01 18:04 UTC
Labels: conflict
