### ISSUE TITLE
Apply donation for

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#81] opened 2015-04-07 04:08 UTC
ENVIRONMENT:

__________________________________________
FEATURE REQUESTS:
Hi Devin

I am in a scenario to build a donation form in which I will most likely have to use Gravity Forms for this build. However To provide decent feedback that will be worthwhile using or taking on board, is a donation form requirement for a foundation charity website. Below Is how I have been given this info in requirement.

Regards,
Ciaran

--------------

Donation form

I would like to make a donation to Foundation Barossa.
❑ $100 	❑ $200 	❑ $500 	❑ $1000 	❑ Other $....................
❑ I would like to pledge $...................a year for ................years. My first donation will be $...........................

I would like my donation to be applied to:
❑ Public Trust Fund (tax deductible)
❑ Barossa Education Trust (tax deductible)
❑ The Open Fund (not tax deductible for donations)
❑ I would like Foundation Barossa to contact me before I nominate one of the above.

❑ Please do not acknowledge my donation publicly

Contact details
Name:
Business:
Phone:
Postal Address:
Email:
Website:

Payment Options
Direct Deposit
Acc name xxx
BSB  xxx
Account number  xxx

Credit Card
We’ll contact you 

Cheque
Please make out to xx and post to to PO Box 616 Nuriootpa SA 5355.
__________________________________________
GENERAL FEEDBACK:
Feedback left on the previous page. :)

REF:345giveCiaran!fgh15

**Comment by DevinWalker** [comment] 2015-04-07 04:25
Interesting form - Particularly the separate checkbox with recurring options and a custom amount. Also, the "Please do not acknowledge my donation publicly" is something we should really put into Core as an option. I feel that would fit nicely along with the terms & agreement option -  @mathetos what do you think?

**Comment by cmwwebfx** [comment] 2015-04-07 04:36
This could be upgraded with an extension as I don't think that all users would need the addition of who to provide the donation to. 

It is a bit unique that in this case we have a foundation that has a few channels to provide donations to, which gives the end user a path where they would like to money to go. This saves building out multiple forms as well if there was an option to select who to provide the money to.

I do realise I can make a form per charity, but this then complicates things for the end user when they choose one, but then decide after completing their name and donation amount that they chose the wrong charity to donate to.

As for adding to core a way the end user can ask that they are kept silent is quite important. Checkbox to be added will be a nice feature for 0.8.

**Comment by DevinWalker** [comment] 2015-04-07 04:41
Agreed, that part of the form is a bit abnormal but I can see why they are doing that because of your explanation. 

What's the plan for the Direct Deposit option? Is that going to be collected through a gateway like WePay? It doesn't look like they want to accept CC payments via a gateway...

**Comment by cmwwebfx** [comment] 2015-04-07 04:51
The direct deposit here in Australia is fairly easy through online banking, so that will not be an issue. But what will be the issue is when they wish to use recurring payments then I will need to enable conditional logic if they choose this option to display only Credit Card via Stripe and hide the manual payment options. 

My thoughts are that this pattern of recurring donation for this form is old fashioned phone "call to follow up" with the donor and ask for them to send a new cheque or direct deposit. 

I still have to discuss the way forward which should be online through PayPal or Strip for this scenario.

**Comment by DevinWalker** [comment] 2015-04-29 05:46
Seeing as this isn't really an "issue" I'm going to close this one out. We'll definitely refer to this RFP form for future enhancements.

**Closed by DevinWalker** 2015-04-29 05:46 UTC
Labels: enhancement
