### ISSUE TITLE
French translation not working properly

### ISSUE THREAD

**Issue by princecaspian** [WordImpress/Give#525] opened 2016-03-14 17:52 UTC
Hi
I have updated Give and I'm using the french translation. But some strings are not translated properly in the front-end and the back-end.
Here's two screenshots : 
<img width="318" alt="capture d ecran 2016-03-10 a 10 03 02" src="https://cloud.githubusercontent.com/assets/1548851/13754058/099d87f8-ea2f-11e5-97fc-313ea14a3014.png">
<img width="1064" alt="capture d ecran 2016-03-10 a 10 03 11" src="https://cloud.githubusercontent.com/assets/1548851/13754059/0bc11c5c-ea2f-11e5-8701-e8faea76f95d.png">

Any idea what's wrong with the translation ? 
Thanks

Regards,

**Comment by DevinWalker** [comment] 2016-06-28 22:19
I just tested with v1.5 which will be released soon and this is fixed. The issue is the current version packages an outdated French translation which does not contain strings for the goal text. Look for that release soon to resolve the issue.

**Closed by DevinWalker** 2016-06-28 22:19 UTC
