### ISSUE TITLE
Incompatibility with PHP 7.1

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1377] opened 2017-01-06 00:13 UTC
## Issue Overview

Users currently cannot use Give with PHP 7.1

## Expected Behavior
We should be current with the latest available PHP version. Siteground for example offers a one-click upgrade to PHP 7.1. 

## Current Behavior
If a user upgrades to PHP 7.1 Give works generally, but not on the Form Edit screen. This is what they see:
![image](https://cloud.githubusercontent.com/assets/930724/21702636/7480e5c6-d361-11e6-803b-9c4c7f9fd630.png)

`Fatal error: Uncaught Error: [] operator not supported for strings in .../wp-content/plugins/give/includes/formatting.php:443 Stack trace: #0 .../wp-content/plugins/give/includes/libraries/cmb2/includes/CMB2_Base.php(283): give_cmb_amount_field_render_row_cb(Array, Object(CMB2_Field)) #1 .../wp-content/plugins/give/includes/libraries/cmb2/includes/CMB2_Base.php(258): CMB2_Base->do_callback('give_cmb_amount...') #2 .../wp-content/plugins/give/includes/libraries/cmb2/includes/CMB2_Base.php(235): CMB2_Base->get_param_callback_result('render_row_cb') #3 .../wp-content/plugins/give/includes/libraries/cmb2/includes/CMB2_Field.php(759): CMB2_Base->peform_param_callback('render_row_cb') #4 .../wp-content/plugins/give/includes/libraries/cmb2/includes/CMB2.php(315): CMB2_Field->render_field() #5 .../wp-content/plugins/give/includes/librari in .../wp-content/plugins/give/includes/formatting.php on line 443

## Steps to Reproduce (for bugs)
The error can currently be seen on this test site (which our team has credentials to internally):
http://php7.mattcromwell.com/donations/standard-form/

That site has been upgraded to PHP 7.1 via Siteground's one-click PHP Version manager.

**Comment by kevinwhoffman** [comment] 2017-01-06 18:28
## Cause

Cause of the error can be found here: https://github.com/WordImpress/Give/blob/master/includes/formatting.php#L437-L443

This error is caused by `$attributes_string` being defined as an empty string on line 437 and then used as an array on line 443. PHP 7.1 doesn't like that.

## Fix

The quick fix is to change the following on line 437 from:
 `$attributes_string = '';` to `$attributes_string = [];`

A proper fix will be incorporated into the next release.

**Comment by kevinwhoffman** [comment] 2017-01-06 18:54
Note the error is caused by a CMB2 function that doesn't exist in `Give 1.8.0` as meta fields are now being handled differently. Need @DevinWalker to weigh in on whether a point release should address this sooner. The error prevents anyone on PHP 7.1 from creating a donation form.

**Comment by ravinderk** [comment] 2017-01-07 01:56
@kevinwhoffman We can not user short tag for now because this will not work in PHP 5.3.
 [] short array syntax introduced in PHP 5.4.

> As of PHP 5.4 you can also use the short array syntax, which replaces array() with [].

For ref: http://php.net/manual/en/migration54.new-features.php

**Comment by kevinwhoffman** [comment] 2017-01-07 01:59
@ravinderk Thanks for the heads up. I edited my fix above to use `array()` instead.

**Closed** 2017-02-13 16:57 UTC
Labels: bug
