### ISSUE TITLE
feat(admin-email): make billing address template tag display in order

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3454] opened 2018-07-10 19:20 UTC
## User Story
As a Site Admin, I want the {billing_address} template tag to output the address in order so that my donors will clearly understand it.

## Current Behavior
I currently have the output show address, city, zip, state. 

## Expected Behavior
I expect to see address, city, state, zip.

## Visuals
![screen shot 2018-07-10 at 3 12 40 pm](https://user-images.githubusercontent.com/20672471/42532364-aeb496e8-8454-11e8-91a3-a01dbb4e0467.png)

## Related
https://secure.helpscout.net/conversation/611374800/20846?folderId=1823994

**Comment by ravinderk** [comment] 2018-07-11 03:53
@samsmith89 Probably duplicate of https://github.com/WordImpress/Give/issues/2790

**Comment by DevinWalker** [comment] 2018-07-11 03:55
Correct @ravinderk

**Closed by DevinWalker** 2018-07-11 03:55 UTC
