### ISSUE TITLE
feat(email): display any meta data with dynamic email tags

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#2801] opened 2018-02-12 19:19 UTC
## Issue Overview

Users often want to display meta data within their emails, but a specific tag for that meta data may not exist. Since `donor` and `donation` meta data are stored in predictable locations, there should be a way for users to define what meta data they want to display through dynamic email tags.

## Expected Behavior

Meta data that is collected should be displayable in emails.

## Current Behavior

Displaying meta data currently requires a specific tag.

## Possible Solution

Add two dynamic email tags capable of reading meta data based on the provided key. The tag would begin with either `donation_` or `donor_` depending on whether the meta data is stored alongside the donation or donor.

Examples:

- `{donation_transaction_id}`
- `{donor_email}`

## Related Issues and/or PRs

https://github.com/WordImpress/Give-Snippet-Library/pull/62

**Comment by ravinderk** [comment] 2018-02-13 03:03
@DevinWalker @mathetos @kevinwhoffman 

I kept in mind when I created the snippet that we cannot create email tags for all donation metadata and there must be an easy way which can handle by admin.

@kevinwhoffman I like the way you suggested tag named but all donation meta does not follow meta key name standard and we do not know which naming will be followed by the third-party addon.
for example: `_give_current_url`, `_give_current_page_id`

This logic is not only for core, but it is for all addon which will be created in future fo give.
That's why I kept it simple `{meta_*}`.

By revisiting the scope of dynamic email tag. I want to add following suggestion.

**Donation** : `{meta_donation_{meta_key}_{array_key|optional} }`
**Donor**: `{meta_donor_{meta_key}_{array_key|optional} }`
**Form**: `{meta_form_{meta_key}_{array_key|optional} }`

Dynamic name details:
`meta_key: meta key name in which you are storing data.`
`{array_key|optional} }: if meta key contains data in an array and you want to get specific data from that array. It will help to get metadata from donation, form, and donor even if it is an array`.

**Comment by kevinwhoffman** [comment] 2018-02-13 03:14
@ravinderk You're much more familiar with the meta architecture than I am, so I trust your judgement on this.

How do you anticipate users knowing which tag to use? Will they be listed alongside the other tags when editing an email template, or will they have to know the `meta_key` from some other source? That list could get pretty long if we list out every key, but I also think users will need these tags spelled out for them in order to understand how to use them.

I suppose even if users don't grasp the feature on their own, it will at least give Support a quick solution for anyone with these kinds of requests.

**Comment by ravinderk** [comment] 2018-02-13 03:45
@kevinwhoffman 

> How do you anticipate users knowing which tag to use? Will they be listed alongside the other tags when editing an email template, or will they have to know the meta_key from some other source? That list could get pretty long if we list out every key, but I also think users will need these tags spelled out for them in order to understand how to use them.

Agree with you. Output list will not be a good idea because the list will keep increasing. On this, we need @mathetos help. Maybe we can document it somewhere or boost an email to plugin users which will inform plugin about it. We can also document general email tag format on email message editor.

> I suppose even if users don't grasp the feature on their own, it will at least give Support a quick solution for anyone with these kinds of requests.

This is the main purpose to develop it.

**Comment by kevinwhoffman** [comment] 2018-02-13 03:47
I agree. A link at the bottom of the existing tags list could point to the documentation for these dynamic tags.

**Comment by mehul0810** [comment] 2018-02-14 10:57
### Slack Call Summary
**_Participants_**: @ravinderk @mehul0810
**_Topic_**: Discussion about meta tag not working for donors
**_Result_**: Showed Ravinder how donor meta email tags are not working and provide a couple of email meta tags which are not working due to blank metadata for donors. `{meta_donor__give_donor_first_name}` and `{meta_donor__give_donor_last_name}`

**Comment by ravinderk** [comment] 2018-02-14 12:01
Slack Call Summary
Participants: @ravinderk @mehul0810
Topic: PR testing
Result: Showed Mehul that all type of meta working fine ( also with FFM)

**Comment by mathetos** [comment] 2018-02-14 14:54
I need to review in more detail, but at first read I think the tags should be prefixed only with `donor_` or `donation_` like discussed in Slack.

But I'll review in more detail in a bit.

**Comment by ravinderk** [comment] 2018-02-14 15:07
@mathetos `donor_`, `donation_` and `form_` is a common prefix, so it can conflict with another tag.
That why created prefix `meta_donor_`, `meta_donation_` and `meta_form_` which also reflect the purpose of this tag means show metadata.

**Comment by mathetos** [comment] 2018-02-14 17:56
@ravinderk That makes sense, I see what you mean and understand. 

I agree with Kevin that adding a link to full documentation would be good. Here's the wording I'd suggest for that sentence and link:

> Additional donation and donor information can be output with custom meta email tags. [See our documentation](http://docs.givewp.com/meta-email-tags) for examples of how to use custom meta email tags in your Give emails.

**Comment by ravinderk** [comment] 2018-02-14 18:16
@mathetos Text added.

![image](https://user-images.githubusercontent.com/1784821/36220601-3a0103c6-11e1-11e8-849d-b58e89157f10.png)

**Comment by mathetos** [comment] 2018-02-14 18:45
@ravinderk A couple things on that:

1) "See our documentation..." should be at the END of the list. It will be the least often used.
2) There should be a line break so that "Available template tags" is on it's own line, separated from the "The email that is sent..." by a blank line.

**Comment by ravinderk** [comment] 2018-02-14 19:04
@mathetos Changes done.

![image](https://user-images.githubusercontent.com/1784821/36222649-01b03652-11e8-11e8-9805-28470efc3999.png)

**Comment by mathetos** [comment] 2018-04-24 23:42
@ravinderk I tested this fully today. Everything seems to work as intended except for the donor meta. I tried with all the variations of the following:

* `{meta_donor__give_stripe_customer_id}`
* `{meta_donor__give_date_created}` or `_give_donor_date_created` etc...

Note that `{meta_donor__give_donor_last_name}` and `first_name` works, but those are already working with existing email tags, it's basically all Donor related tags that are NOT already existing email tags. 

Also note that `meta_donation_` and `meta_form_` tags are working just as intended. 

I want to fully document this new feature but it need to be able to see it correctly. If you test and have it working then let me know what I'm missing. Otherwise, maybe we should re-open this until those tags work as intended.

**Comment by ravinderk** [comment] 2018-04-25 03:37
@mathetos 
1. can confirm that `_give_stripe_customer_id` metadata creates before email send?
2. `_give_date_created` is not donor meta but it seems you want `date_created` which is part of donor table. I added support for it. You will data directly from donor table if not find in donor meta table. `{meta_donor_id}`, `{meta_purchase_count}` etc.
https://github.com/WordImpress/Give/compare/48226592010f...ee827d8c1967

**Comment by mehul0810** [comment] 2018-04-26 05:55
@mathetos @ravinderk 
I've tested this and both the email tags ( i.e. `{meta_donor__give_stripe_customer_id}` and `{meta_donor_date_created}` ) are working fine. For email tag `` there is an issue when the test mode is enabled. You can check the condition in `give_stripe_get_customer_key` fn.

**Comment by mathetos** [comment] 2018-04-26 17:57
Thanks for testing @mehul0810  -- I pulled the latest 2.1 and `{meta_donor_date_created}` is working as intended now. 

Regarding `{meta_donor__give_stripe_customer_id}` I looked at the `give_stripe_get_customer_key` function which says basically to append `_test` to the end, I did that like so: `{meta_donor__give_stripe_customer_id_test}` and all worked well as well.

Thanks! I'll close this out again.

**Closed by mathetos** 2018-04-26 17:57 UTC
