### ISSUE TITLE
fix(clone-forms): remove donations associated with a cloned/duplicated form upon duplication

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#3456] opened 2018-07-10 21:40 UTC
## User Story
As a `give admin`, I want `cloned/duplicated forms to have no donations associated with them` so that `my data appears accurate on the Forms page`.

With the fix to https://github.com/WordImpress/Give/issues/3331 there's now a method in 2.2 for cloning/duplicating a form. 

When the form is duplicated, it still shows the number of donations from the previous form on it. 

This is easily remedied by recalculating the data at tools > Data, but admins should not have to do that. 

## Current Behavior
I currently duplicate the form, and then save it, only to go back to All Forms and see an incorrect number of donations and amounts associated with it. 

## Expected Behavior

I expect to see the correct number (0) of donations associated with a brand new form.

## Possible Solution
Add a step in the clone form class that recalculates the data for that form upon creation.

## Related

- https://github.com/WordImpress/Give/issues/3331

## Tasks

- [ ] remove old data from duplicated forms

**Comment by kevinwhoffman** [comment] 2018-07-10 21:51
@Sidsector9 Assigning to you since you wrote the cloning functionality and are familiar with it. In addition to donations, please review and make sure that any meta data generated as the result of a donation is not carried over to the new form. The new form should only inherit the settings of the old form.

**Comment by kevinwhoffman** [comment] 2018-07-10 22:03
@ravinderk Also please leave your thoughts as to whether there are any add-ons to be aware of that add meta data to the form which should NOT be carried over into the cloned form.

**Comment by ravinderk** [comment] 2018-07-11 05:28
@Sidsector9 @Benunc  it has been fixed. Let me know if you can reproduce this.

We created separate issue for fee recovery https://github.com/WordImpress/Give-Fee-Recovery/issues/217

**Closed by ravinderk** 2018-07-11 05:28 UTC
Labels: high-priority
