### ISSUE TITLE
fix(form): display actual goal progress even after goal is met

### ISSUE THREAD

**Issue by marutim** [WordImpress/Give#2638] opened 2018-01-09 10:35 UTC
## Issue Overview
When the donation goal format is set to percentage. It is set to show the correct percentage upto 100%. Once the donation is fully funded it keep showing 100% instead of showing the correct figure which should be greater than 100%.

But when the goal format is set to amount it always shows the correct figure no matter the donation is fully funded or not.

## Expected Behavior
It should show the correct figure in percentage like it shows for the donation goal when set for amount format.

## Current Behavior
It shows correct figure until 100% and then stuck at 100% only.

## Possible Solution
There is a conditional in the code which check if the percentage is greater equal to 100% ,if yes it sets the variable to 100% else to the actual value. We can remove that conditional and let the actual figure in percentage display.

## Steps to Reproduce (for bugs)
1. Check this in a donation form which has exceeded the goal amount.
2. First set it to Amount and then check the donation goal in the front end. You would see the correct figure.
3. Now set the goal format to percentage and then check the front end again, you would see 100% and not the correct figure.

## Related Helpscout ticket
https://secure.helpscout.net/conversation/495071541/12794/?folderId=1457790

## Screenshots
![1](https://user-images.githubusercontent.com/3498917/34716673-8eedae54-f556-11e7-8afd-8ac1ee6a0605.png)
![2](https://user-images.githubusercontent.com/3498917/34716674-8ffb9478-f556-11e7-8c5b-58d040977e0c.png)

**Comment by malayladu** [comment] 2018-01-10 11:46
Interesting thing.

I am thinking that whether we should allow accepting donation after getting 100% fund. 

@marutim & @DevinWalker What's your thought on this?

**Comment by marutim** [comment] 2018-01-10 12:02
@malayladu I can not think of a reason why we should not. We already have the option for the admin to set an option where the donation form would close automatically when the donation is fully funded. So this entirely depends on the admin to decide how they wants to go with the funding post fully funded. 

Give has all the ammunition loaded, it is on the site owner/admin to decide how to fire those ;)

**Comment by malayladu** [comment] 2018-01-10 12:23
@marutim Ok. Got it.

I think 100% funded would be ok instead of showing 125% funded. I am not sure but it may create a bad impact on donor's mind.

If we show percentage above 100 then donor might think twice before making further donation. This is my perspective. This might not be the case.

**Comment by ravinderk** [comment] 2018-01-10 13:56
@malayladu You also raised a valid point.  Showing `125%` can change donor mind.

@DevinWalker I think if somebody wants to edit percentage then they can use `give_goal_output ` filter.

**Comment by marutim** [comment] 2018-01-10 14:01
I am all in for an option to change that behaviour we have currently. May it be by an option in the settings page or a filter. Anything will be helpful :)

**Comment by slewisma** [comment] 2018-01-10 14:07
My opinion from running Give on several customer sites:
100% is just as likely to keep a donor from giving as 125%. 

If the org doesn't want to show > 100%, they should close the campaign at 100% and redirect to a standard donation form for those that want to give anyway.

Showing > 100% can motivate more giving if the campaign is positioned with the goal as the minimum needed and exceeding the goal is promoted as being even better for the cause. 

I'd either make it configurable or allow > 100% in the default case.

**Comment by ravinderk** [comment] 2018-01-10 14:24
@slewisma Thank you for your opinion. Currently, you can achieve this with custom code. We are in discussion to adding this to the core or not.

@DevinWalker @marutim  I created a mockup. Let me know what do you think.

![image](https://user-images.githubusercontent.com/1784821/34777237-b202063a-f63f-11e7-80f0-72250ad567cf.png)

**Comment by DevinWalker** [comment] 2018-01-11 07:20
Thanks for the mockup @ravinderk and everyone for the discussion here. It's an interesting request and I do kind of like the option, but I'm just wondering how many people _actually_ want this and maybe a snippet will be better?

I see people wanting more than just to _end_ the progress displayed once the goal has been achieved. For instance, they may want to swap out the message entirely to say "Fully funded!". The option as it is now won't allow them to do that.

As well, it only is working with percentages. What about "Amount" and "Number of Donations"? The option should be relevant for those three as well, right?

How about the option is titled:

Title: "Goal Met" 
Desc: "When a goal as met how would you like the text above the progress bar to display? For instance, you can say "Fully funded!", display a full value like "100%" or "60 of 60 donations", or continue displaying progress like "125% of 100%". 

What do you think of that?

**Comment by kevinwhoffman** [comment] 2018-03-12 02:57
There is precedent for displaying percentages and amounts greater than the goal in both Kickstarter and Indiegogo, and users (especially in crowdfunding) expect the goal to continue updating the actual amount raised even after the goal is met.

While an overfunded goal may dissuade some donors from giving, it may convince others to give when they otherwise would not because they are convinced by the social proof of an overfunded campaign. Again, in crowdfunding, an overfunded goal is a good sign that the product comes from a trustworthy source. Whatever the effect, showing the actual amount raised is the most honest and transparent behavior that provides the donor with accurate information.

As @marutim mentioned, if it is not the campaign owner's intent to raise more than the goal , then they can choose to close the form when the goal is met. But if they do want to raise more, then we should indicate that by displaying the actual amount.

## Kickstarter Amount Goal

![image](https://user-images.githubusercontent.com/1938671/37263022-a9c21656-257c-11e8-8bbe-6aa0f9d3105f.png)

## Indiegogo Percentage Goal

![image](https://user-images.githubusercontent.com/1938671/37263047-bc0c770c-257c-11e8-8435-9ef3f8b520eb.png)

## Recommended Solution

Keep the existing form options exactly as they are and update the behavior to display the actual amount, percentage, or number of donations, even after

**Comment by DevinWalker** [comment] 2018-03-12 18:03
I agree with @kevinwhoffman above about our default functionality. Steps to closing this one out include:

### Steps to Resolve

- [ ] Update the goal output behavior to display the actual amount, percentage, or number of donations, even after the goal is met.

**Closed** 2018-03-15 00:10 UTC
