### ISSUE TITLE
Plugin loads resources in non-performant ways.

### ISSUE THREAD

**Issue by Stegosource** [WordImpress/Give#1211] opened 2016-11-04 21:58 UTC
## Issue Overview

 When the Give plugin is installed, the CSS and JS files are loaded on every page, regardless if the shortcodes are present. Also, the JS files should be loaded in the footer.

## Expected Behavior

Resources should only be loaded when used. JS should load in the footer.

## Current Behavior

Resources are loaded on every page

## Possible Solution

Replace wp_enqueue_script/style with wp_register_script/style, then add wp_enqueue_script/style with their respective handles within the shortcode output functions so the resources will only be output when the shortcode is used. 

Pass a 'true' statement to the $in_footer argument in wp_enqueue_scripts. This will load the script in the footer. See https://developer.wordpress.org/reference/functions/wp_enqueue_script/

## Steps to Reproduce (for bugs)

1. Install plugin
2. View page source

**Comment by DevinWalker** [comment] 2016-11-04 22:09
The issue is it's very hard to accurately tell whether or not a site's page/post has a shortcode or widget in use. This is because there are many different so many different ways to include Give. You can output in your content, which is easy to discover, or within a PHP file like a page template using `do_action`, where it's harder to tell, or nested in shortcodes via a plugin like Visual Composer. 

There just isn't a reliable way to accurately tell is a certain page is using Give and then conditionally load scripts. I've researched extensively handling script loading better. 

As well, it's becoming best practice to minify and concat JS/CSS for the entire site so that it's loaded once upon visit and cached thereafter. Plugins like WP Rocket do this pretty well. 

Let me know your thoughts.

**Comment by Stegosource** [comment] 2016-11-04 22:20
The plugin outputs the forms from a shortcode right? You could enqueue the resources right from within the shortcode callback. Or, if it's in a widget, include it in the widget callback. 

This way, if the shortcode is called from the content, or do_shortcode(), or in a widget, or in Visual Composer (uses the shortcode), it will all work, and will not load unnecessary resources.

Here's a good article with more details: https://iandunn.name/2011/07/01/conditionally-loading-javascript-and-css-in-wordpress-plugins/

**Comment by DevinWalker** [comment] 2016-11-04 22:53
It does output the forms via a shortcode, that's correct. There are several other shortcodes as well, `[donation_history]`, `[give_form]`, `[give_goal]`, `[give_login]`, `[give_register]`, `[give_receipt]`, `[give_profile_editor]`.  Your suggestion is that for each of these shortcodes we enqueue just the JS scripts? The CSS will need to remain in the `<head>` for all pages but the script loading defers to the footer by default.

**Comment by DevinWalker** [comment] 2016-11-04 22:58
FYI we have this snippet for conditional loading: https://github.com/WordImpress/Give-Snippet-Library/blob/master/theme-compatibility/conditional-script-loading.php

**Comment by Stegosource** [comment] 2016-11-04 23:05
Yeah, so you would register the scripts and styles in one place with a handle. Then in each shortcode callback, enqueue the handle for the CSS and/or JS as needed for that specific shortcode. Then regardless whether you have 1, 2, or many shortcodes on the same page, the resources would be enqueued. And Im not saying this is JUST for the JS. I think this could be done safely for CSS and JS and would be a perfomance gain. 

As for the JS in the footer, I dont know if it's true that it goes in the footer by default. We have this file showing up in the head: /plugins/give/assets/js/frontend/give.all.min.js?ver=1.6.3

And also, according to the WP codex, the $in_footer parameter is false by default: 

https://developer.wordpress.org/reference/functions/wp_enqueue_script/

wp_enqueue_script( string $handle, string $src = false, array $deps = array(), string|bool|null $ver = false, bool $in_footer = false )

**Comment by DevinWalker** [comment] 2016-11-04 23:09
Loading CSS in the footer will cause a flash of unstyled content (FOUC) for the elements. We do load JS in the header by default. There's an option under Settings > Advanced > Load Scripts in Footer. I'm not opposed to doing some optimization but want to proceed with caution.

**Comment by Stegosource** [comment] 2016-11-04 23:14
OK, wait. CSS in the header for sure. I never said anything about CSS in the footer. Just JS with wp_enqueue_script() not style. 

Anyway, I think this is a good way to go. JS can stay in the header if you feel it should be there, and the option in the backend satisfies that requirement anyway. I just saw that it was in the header by default. Not a big deal either way. 

But for both CSS and JS, it's possible to only load those resources when the shortcode is present by calling the enqueue functions within the shortcode callback.

We can talk more on this if you like in person or phone. If I get some time I might make a PR, but pretty busy right now so it wouldn't be for a while.

**Comment by DevinWalker** [comment] 2016-11-04 23:16
@Stegosource hit me up in the Give Community Slack - Developer channel when you get a chance.

**Comment by mathetos** [comment] 2018-03-02 20:13
Current thoughts:
Make this a setting in "Settings > Advanced" and have the default be Globally loaded. Like so:

**Setting name:**
"Conditional Script Loading"

**Options:**
"Globally"  ||  "When a Form is Present"

**Description:**
This setting determines whether the scripts are loading globally throughout the website, or only when a form is present on the page

**Comment by kevinwhoffman** [comment] 2018-03-28 01:58
Closing with the expectation that Gutenberg will allow us to detect Give block usage and enqueue scripts accordingly.

**Closed by kevinwhoffman** 2018-03-28 01:58 UTC
