### ISSUE TITLE
feat(admin-setting): add chosen when selected Base Country

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#3117] opened 2018-04-25 16:56 UTC
## User Story

As an `Admin`, I want chosen in Base Country Search so that it will be easy for me admin to find the specific country.

## Current Behavior
I currently have top browse all the country and search for a specific country 

## Expected Behavior
I expect to that it should have chosen search featured 

## Visuals
![image](https://user-images.githubusercontent.com/22215595/39260633-b2a2a4d8-48d7-11e8-84e3-299a9ee94d7c.png)

**Comment by ravinderk** [comment] 2018-04-26 03:53
@raftaar1191 closing this because duplicate of https://github.com/WordImpress/Give/issues/2423

**Closed by ravinderk** 2018-04-26 03:53 UTC
