### ISSUE TITLE
Transaction Status Bulk Change not reflected

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#79] opened 2015-04-02 20:03 UTC
I changed these statuses with the "Bulk Action" tool, the icon went grey and there is no Status text now. And when I click on "View Details" it shows the old status but the icon is grey.
![transactions-bulk-change-no-status](https://cloud.githubusercontent.com/assets/930724/6972437/9149bc2a-d938-11e4-9ca2-91843a759460.png)

**Comment by DevinWalker** [comment] 2015-04-07 04:38
@mathetos I just tried to reproduce this and was not able to. Can you please pull down the latest code and try to reproduce again in at least two separate environments?

**Comment by DevinWalker** [comment] 2015-04-10 21:07
Closing until @mathetos can reproduce

**Comment by mathetos** [comment] 2015-04-11 17:30
Just emailed you another example of this after I reproduced it on a live site.

**Comment by DevinWalker** [comment] 2015-04-29 04:58
@mathetos for some reason I still can't reproduce this anywhere. I want to get this issue closed out so let's see if we can figure this out ASAP - if you could take a stab at it, even better.

**Comment by DevinWalker** [comment] 2015-05-02 19:29
I'm going to move this from the 0.9 Milestone until we can figure out how to reproduce it.

**Comment by DevinWalker** [comment] 2015-06-03 23:12
Assigning back to you @mathetos until you can reproduce it :+1:

**Closed by DevinWalker** 2015-06-03 23:12 UTC
Labels: invalid
