### ISSUE TITLE
Recalculate Income Amount and Donation Counts for All Forms tool is not working

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1905] opened 2017-07-21 17:59 UTC
## Issue Overview

I faced this issue in `release/1.8.12` branch.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment] 2017-07-24 23:51
@mehul0810 is this fixed with the merge of Recurring PR 360?

**Comment by mehul0810** [comment] 2017-07-25 02:31
@DevinWalker Yes. this is fixed as the issue is with Give Recurring Addon.

**Closed** 2017-07-25 04:46 UTC
Labels: bug
