### ISSUE TITLE
CMB2 Inclusion

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#77] opened 2015-04-02 17:40 UTC
ENVIRONMENT:
I have a simple install of Wordpress with 2 plugin installed that both use CMB2.
___________________________________________

BUGS:
I'm pretty sure that the bug is related to how you are enqueuing your copy of CMB2.  In my plugin, I enqueue it through composer's autoload, and it work until I turn your plugin on. At first, I thought it might have been mine, but I added another plugin that I have that uses the CMB2 which is also installed with composer and there is no conflict
___________________________________________

SCREENSHOTS:
https://givewp.com/wp-content/uploads/gravity_forms/1-a1eca7ec4ac2cce1aa3799851babf19e/2015/04/cmb2-error.jpg
___________________________________________

GENERAL FEEDBACK:
Looks like a good plugin so far.
___________________________________________
REF: 789giveAndrew!ghs15z

**Comment by DevinWalker** [comment] 2015-04-07 02:55
I just tested with CMB2 plugin activated and also @mathetos own plugin that uses CMB2 - no issues. I'm closing this one out as I'm unable to reproduce.

**Closed by DevinWalker** 2015-04-07 02:55 UTC
Labels: bug
