### ISSUE TITLE
Consider adding [give_total_donations] shortcode

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1909] opened 2017-07-24 16:46 UTC
## Issue Overview
Users often request having a way to output the totals of multiple forms. We generally point them to this shortcode snippet that we created, and we've iterated on that snippet quite a bit over the last year:
https://github.com/WordImpress/Give-Snippet-Library/blob/master/custom-shortcodes/total-earnings-shortcode.php

We should consider incorporating it into Core in one form or another.

**Comment by mathetos** [comment] 2017-12-15 21:10
@DevinWalker I've gotten probably 3-4 requests for this shortcode a week for the past few weeks. Would love to tie this to a Milestone soon if possible.

**Comment by DevinWalker** [comment] 2018-01-27 00:57
Closing as duplicate of https://github.com/WordImpress/Give/issues/1472

@mathetos please correct me if this isn't a duplicate but it looks like the same functionality.

**Closed by DevinWalker** 2018-01-27 00:57 UTC
Labels: enhancement

**Comment by mathetos** [comment] 2018-01-29 19:52
No you're right, duplicate for sure.
