### ISSUE TITLE
Setting - General Tab: Form fields

### ISSUE THREAD

**Issue by stegosource** [WordImpress/Give#57] opened 2015-03-19 23:20 UTC
Form fields should be prepopulated with default pages (like how Mailpoet and Woocommerce do 			this). And it looks like default pages are loaded in form fields based on post date and time. I would recommend creating the pages in order so that their order matches the form input order.

In other words, create them in this order: History, Transaction Failed, Confirmation. So that when the fields are loaded, the are in their respective places in the dropdown (Confirmation, Transaction Failed, History). 

Subtle UI suggestion.

**Comment by DevinWalker** [comment] 2015-03-19 23:37
This is a duplicate of #40

**Closed by DevinWalker** 2015-03-19 23:37 UTC
