### ISSUE TITLE
Give Importer: Attachment ID showed instead of File name after selection

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2133] opened 2017-09-27 03:32 UTC
## Issue Overview
After selecting the CSV file for import procedure, File name should be shown in file field instead of attachment number.

<img width="762" alt="importer_file_name" src="https://user-images.githubusercontent.com/1852711/30894569-2ff7f0d0-a362-11e7-8a29-10d297a1430c.png">

## Expected Behavior
CSV File Name should be shown after selection

## Current Behavior
Attachment ID of CSV File is shown after selection

## Possible Solution
Changing the pointer from attachment id to attachment name will help.

## Steps to Reproduce (for bugs)
1. Install Give
2. Go to `Tools > Import`
3. Select a CSV file to import
4. You will notice that number is shown after selection instead of file name.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment] 2017-09-27 03:50
i discussed this with @raftaar1191 and he mentioned there was some issue with using the URL. I agree it looks better from a user experience perspective.

**Comment by ravinderk** [comment] 2017-09-27 03:52
@raftaar1191 We can use `hidden` field which will contain attachment ID and `text` field will contain the only file name. This will resolve both logic and UI problem.

Let me know what do you think

**Comment by DevinWalker** [comment] 2017-09-27 03:59
@ravinderk that's what I was thinking too

**Comment by raftaar1191** [comment] 2017-09-27 08:21
Yes, @ravinderk  we can do that 

Thanks for the suggestion

**Comment by mathetos** [comment] 2017-09-28 23:55
I think this needs to be re-opened. The validation seems to still be looking for an ID instead of a URL. See here:
![image](https://user-images.githubusercontent.com/930724/30995254-c6d6d744-a46d-11e7-8232-3f2b92d74524.png)

**Comment by ravinderk** [comment] 2017-09-29 01:10
@mathetos for internal logic we are using `ID`, so you can say url just a `UI` thing for admin, but still, the message is not correct.

`Please upload or provide a valid CSV file`

Let me know what do this think about above message

**Comment by mathetos** [comment] 2017-09-29 01:13
The problem isn't the message as much as the importer does not continue from that point. I get that error and cannot go forward. Whether it shows the full URL or the ID, it should continue when a valid CSV file is uploaded and selected (which it was in this case).

I can provide you with the CSV via Slack -- it has live donor info in it.

**Comment by ravinderk** [comment] 2017-10-02 04:41
@DevinWalker @mathetos  Closing this issue because it is resolved directly into `release/1.8.14`. Let me know if you able to reproduce this issue again.

**Closed by ravinderk** 2017-10-02 04:41 UTC
Labels: question, UI / UX
