### ISSUE TITLE
Ability to Adjust Payment Gateway Order Easily

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#276] opened 2015-09-28 18:26 UTC
It would be useful to allow users to designate the order by which the payment gateways appear on their donation forms. Currently, it seems all premium Gateways are always put behind the default gateways. Of course, allowing to choose the default gateway is helpful, it's still relatively odd to put "PayPal Pro" at the very end of the list and enabled as the default.

Related ticket: https://givewp.com/support/ticket/pdf-receipt-order-of-payment-methods-on-give-form/

**Comment by mathetos** [comment] 2015-09-28 18:27
I didn't see an easy way to use a filter for this, but I assume we'd have to add some kind of sorting logic to the `give_get_enabled_payment_gateways()` function.

**Comment by DevinWalker** [comment] 2015-10-07 05:32
I would love to add the ability to drag-and-drop gateways in the specific order you see fit - globally and per form. Add-on territory? Is this even necessary, or simply nice to have?

**Comment by DevinWalker** [comment] 2015-10-07 05:33
Updated title to be more verbose and descript

**Comment by DevinWalker** [comment] 2016-05-19 18:43
This is a duplicate of #391

**Closed by DevinWalker** 2016-05-19 18:43 UTC
Labels: enhancement, feature request
