### ISSUE TITLE
Email confirmation

### ISSUE THREAD

**Issue by lcpstudio** [WordImpress/Give#1359] opened 2016-12-22 20:34 UTC
## Issue Overview

I wanted to use a confirmation input for the email adress

## Expected Behavior

Give ask for an email; it would be perfect to have this email address checked.

## Possible Solution

Here is a code to do it:

//Adding the input

function Ajouter_Champs_Perso( $form_id ) {?> 

<p>
 <div id="floatlabel floatlabel-give-email is-active">
<input class="give-input required floatlabel-input" type="email" name="give_mail2" id="give-give_mail2" placeholder="Confirmer votre adresse email" required="" aria-required="true">
  <label class="give-label" for="give-give_mail2"></label> 
  </div>
 </p>
  <?php }
  
 add_action( 'give_purchase_form_after_personal_info', 'Ajouter_Champs_Perso', 10, 1 );

//Check if the email addresses are the same

function Verifier_Confirmation_Email( $valid_data, $data ) {
	if ( $data['give_email'] != $data['give_mail2']) {
		give_set_error(  'give_mail2', __( 'Les deux emails ne correspondent pas.', 'give' ) );
	}
}

add_action( 'give_checkout_error_checks', 'Verifier_Confirmation_Email', 10, 2 );

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Related PRs
List related PRs against other branches:

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mathetos** [comment] 2016-12-22 20:37
Thanks for reporting this and for your code snippet @lcpstudio

**Comment by lcpstudio** [comment] 2016-12-22 20:39
My pleasure !

**Comment by DevinWalker** [comment] 2017-01-26 07:22
Duplicate of https://github.com/WordImpress/Give/issues/1038

**Closed by DevinWalker** 2017-01-26 07:22 UTC
