### ISSUE TITLE
Unable to change donation level within donation details edit screen

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2280] opened 2017-11-02 06:39 UTC
## Issue Overview
When I attempt to change the donation level using the dropdown I am unable to do so:

![2017-11-01_23-36-33](https://user-images.githubusercontent.com/1571635/32312936-9cf53492-bf5d-11e7-801e-86a0c36ac3ad.gif)

## Expected Behavior
The level should change the amount accordingly and it should also work with Fee Recovery by adjusting the amount plus the fees:

![2017-11-01_23-38-12](https://user-images.githubusercontent.com/1571635/32312979-ca96e3f0-bf5d-11e7-8284-0712cc606bc3.png)

## Current Behavior
Only manually changing the amount works. The dropdown is useless.

## Steps to Reproduce (for bugs)
1. Give + Fee Recovery
2. View a donation on multi-level form
3. Attempt to change the level and save

**Comment by ravinderk** [comment] 2017-11-06 03:29
@DevinWalker I was unable to reproduce this in `release/1.8.17`. I merged pr by @jaydeeprami 
 which contain some code improvement changes only.

Let me know if you still can reproduce this.

**Comment by DevinWalker** [comment] 2017-11-07 18:27
I am able to reproduce it in two separate environments:

![2017-11-07_10-24-08](https://user-images.githubusercontent.com/1571635/32510568-e392137e-c3a5-11e7-8cb6-4830cb14aff9.gif)

![Uploading 2017-11-07_10-26-12.gif…]()

**Comment by raftaar1191** [comment] 2017-11-09 19:24
@DevinWalker @ravinderk able to generate the issues

Working on this

**Comment by raftaar1191** [comment] 2017-11-10 06:41
When I attempt to change the donation level using the dropdown I am unable to do so:
-> Works with Give Core Version 1.8.16

**Comment by raftaar1191** [comment] 2017-11-10 12:14
Here is the commit which is creating the issues 
https://github.com/WordImpress/Give/commit/37000d78cc5cc6f835f6469a432a8807bfdeef1d#diff-2847c2e10acbb82484800d222392b7a6R69


https://codex.wordpress.org/Function_Reference/absint
Notes: absint does not allow the decimal value

**Closed** 2017-11-13 03:56 UTC
Labels: bug, has pr
