### ISSUE TITLE
feat(form): ensure custom amount is never less than minimum amount

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2819] opened 2018-02-16 10:04 UTC
## Issue Overview
It will be good fix if we set the Custom Amount value to the Minimum Amount at the time when user click on it Custom Amount ( button/Dropdown/radio ) and if user left it blank then it should be again default set to the minimum amount

**Notes: It's working when we put Amount greater then ZERO but less then Donations minimum amount but not when the amount is set to ZERO* 

## Expected Behavior
User should set the the value to zero, If the Minimum amount is 1

## Current Behavior
User can set the the value to zero, If the Minimum amount is 1

## Steps to Reproduce (for bugs)
See the Video

## Video link
Video Link: https://screencast-o-matic.com/watch/cFnD6eos4S

![image](https://user-images.githubusercontent.com/22215595/36302428-72d8fa5c-132e-11e8-9228-591b1674f3c7.png)

![image](https://user-images.githubusercontent.com/22215595/36302511-bb7a3e7e-132e-11e8-9c26-dc885d3e789c.png)

## Todos
- [x] Tests
- [x] Documentation

## WordPress Environment
<details>
```
### WordPress Environment ###

Home URL: http://give20.local
Site URL: http://give20.local
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give20.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.4
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: 2.0.3
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give20.local/donation-confirmation/
Failure Page: http://give20.local/donation-failed/
Donation History Page: http://give20.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###


### Other Active Plugins ###

Duplicate Post: by Enrico Battocchi – 3.2.1

### Inactive Plugins ###

Braintree For WooCommerce Free: by Payment Plugins, support@paymentplugins.com – 2.6.20
Braintree WooCommerce Addon: by Syed Nazrul Hassan – 1.0.0
Charitable: by WP Charitable – 1.5.9
Give - 2Checkout Gateway: by WordImpress – 1.0.2
Give - Authorize.net Gateway: by WordImpress – 1.3.3
Give - AWeber: by WordImpress – 1.0.2
Give - Braintree Gateway: by WordImpress – 1.1.1
Give - CCAvenue Gateway: by WordImpress – 1.0
Give - ConvertKit: by WordImpress – 1.0.1
Give - CSV Toolbox: by WordImpress – 1.0
Give - Development Plugin: by Raftaar1191 – 1.0.0
Give - Display Donors: by WordImpress, LLC – 1.0
Give - Dwolla Gateway: by WordImpress – 1.1.2
Give - Email Reports: by WordImpress – 1.0
Give - Fee Recovery: by WordImpress – 1.3.8
Give - Form Countdown: by WordImpress – 1.0
Give - Form Field Manager: by WordImpress – 1.2.6
Give - Gift Aid: by WordImpress – 1.1
Give - Google Analytics Donation Tracking: by WordImpress – 1.1.1
Give - MailChimp: by WordImpress – 1.3.7
Give - Manual Donations: by WordImpress – 1.2.2
Give - Paymill Gateway: by WordImpress – 1.1
Give - PDF Receipts: by WordImpress – 2.2.4
Give - Recurring Donations: by WordImpress – 1.5.5
Give - Stripe Gateway: by WordImpress – 1.5.2
Give - Tributes: by WordImpress – 1.3.6
Loco Translate: by Tim Whitlock – 2.0.17
Polylang: by Frédéric Demarle – 2.3
WooCommerce: by Automattic – 3.3.1
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.1.1
WP Hide & Security Enhancer: by Nsp Code – 1.4.7.6
WPS Hide Login: by Remy Perona for WPServeur – 1.2.1

### Theme ###

Name: Twenty Sixteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

```
</details>

**Comment by DevinWalker** [comment] 2018-02-28 03:23
I found a JS bug with this due to the value changing from `custom` to an amount - reopening:

![2018-02-27_19-23-10](https://user-images.githubusercontent.com/1571635/36768358-a895fe24-1bf3-11e8-9314-1dcb710cf6f9.png)

**Comment by ravinderk** [comment] 2018-02-28 05:54
@raftaar1191 
I found issue with `Recurring` addon.

Steps to reproduce:
1. Create a form with custom amount active.
2. set minimum custom amount to `10.00`
3. Try to switch to custom amount

![image](https://user-images.githubusercontent.com/1784821/36772046-a511e80e-1c79-11e8-9631-1bf1465b609b.png)

**Comment by DevinWalker** [comment] 2018-02-28 20:39
I'm going to close this issue because right now the functionality works pretty well and we should shift focus on revamping the entire form experience rather than nit picking minor UI issues in the current one.

**Closed by DevinWalker** 2018-02-28 20:39 UTC
Labels: enhancement
